name:                picca
version:             0.1.0.0
license:             MIT
build-type:          Simple
cabal-version:       ">=1.10"

library
  exposed-modules:     Builder.PiccaBuilder
                       Domain.Picca
                       Domain.PiccaRepository
                       Facade.PiccaFacade
                       Logger.PiccaLogger
  hs-source-dirs:      src
  build-depends:       base >=4.7 && <5
                       time
  default-language:    Haskell2010

test-suite picca-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             TestPicca.hs
  build-depends:       base >=4.7 && <5
                       picca
                       HUnit
                       time
  default-language:    Haskell2010

executable picca
  main-is:             Main.hs
  hs-source-dirs:      app
  build-depends:       base >=4.7 && <5
                       picca
  default-language:    Haskell2010
